import Head from "next/head";
import Image from "next/image";
import { useAuth } from "../lib/auth";
import styles from "../styles/Home.module.css";

export default function Home() {
  const auth = useAuth();
  console.log(auth?.user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!auth?.user && (
          <button
            onClick={(e) => {
              auth.signinWithGithub();
            }}
          >
            Sign In
          </button>
        )}
        {auth?.user && (
          <button
            onClick={(e) => {
              auth.signout();
            }}
          >
            Sign Out
          </button>
        )}
        <div>{`${auth?.user?.email}`}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
