import Head from "next/head";
import Image from "next/image";
import { useAuth } from "lib/auth";
import styles from "styles/Home.module.css";
import { Button, CSSReset, Heading, Text } from "@chakra-ui/react";

export default function Home() {
  const auth = useAuth();
  console.log(auth?.user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Fast Feedback App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>Fast Feed Back App</Heading>
        {!auth?.user && (
          <Button
            onClick={(e) => {
              auth.signinWithGithub();
            }}
          >
            Sign In
          </Button>
        )}
        {auth?.user && (
          <Button
            onClick={(e) => {
              auth.signout();
            }}
          >
            Sign Out
          </Button>
        )}
        <Text>{`Current User: ${auth?.user?.email}`}</Text>
        <Text>{`Current User: ${auth?.user?.displayName}`}</Text>
        <Text>{`UID: ${auth?.user?.uid}`}</Text>
        <Text>{`Current User: ${auth?.user?.email}`}</Text>
        <Text>{`Current User: ${auth?.user?.email}`}</Text>
      </main>

      <footer className={styles.footer}>FOOTER</footer>
    </div>
  );
}
